### ISSUE TITLE
error on JHMDB_dloader.py

### ISSUE THREAD

**Issue by desperate1998** [Yuexiaoxi10/Key-Frame-Proposal-Network-for-Efficient-Pose-Estimation-in-Videos#2]
Hello, dear author, it is a pity that I can not run your code successfully. Although I tried my best to solve it, it can not work correctly. Here are my problems.

When I run the JHMDB_dloader.py, setting parameter split as ‘val’, it just process 3 data items, when setting it as 'test', it can process 19 data, but they are both less than what I provide.
We have tried pytorch version 0.4.0,.0.4.1 and 1.0.0, but it failed.
We have done some change, deleting the key--baseline from the return(dict) of function: __getitem__().
We have a guess that we do not generate Bbox.mat correctly. Here are my code to get Bbox.mat.

`matDataPath = '/home/mxz/pose_estimation/JHMDB/puppet_mask';    

matDataDir1  = dir(matDataPath);             
matDataSubDir1=matDataDir1(3:end);      
numSubDir1=length(matDataSubDir1);      

for vnumSubDir1=1:numSubDir1
    matDataPath1=strcat(matDataPath,'/',matDataSubDir1(vnumSubDir1).name);
    matDataDir2  = dir(matDataPath1);    
    matDataSubDir2=matDataDir2(3:end);
    numSubDir2=length(matDataSubDir2);

    for vnumSubDir2=1:numSubDir2
        matDataPath2=strcat(matDataPath,'/',matDataSubDir1(vnumSubDir1).name,'/',matDataSubDir2(vnumSubDir2).name,'/','*.mat');
        matFiles=dir(matDataPath2);
        numFiles=length(matFiles);
        
        str1=strcat(matDataPath,'/',matDataSubDir1(vnumSubDir1).name,'/',matDataSubDir2(vnumSubDir2).name,'/','puppet_mask.mat');
        fprintf('the value of str1 is %s\n',str1);
        
        mask=load(str1);
        str2=strcat(matDataPath,'/',matDataSubDir1(vnumSubDir1).name,'/',matDataSubDir2(vnumSubDir2).name,'/','Bbox.mat');
        dim3 = size(mask.part_mask,3);
        Bbox =zeros(dim3,4);
        for dim=1:dim3
            Bbox_row=getBox(mask.part_mask(:,:,dim));
            Bbox(dim,:) = Bbox_row;
        end
        save(str2,'Bbox');
    end
end`

If my code is wrong, could you send me a copy of your code?

Here are the error infos:
situation 1: setting parameter, split as 'val'
`/ECCV20 Key-Frame-Proposal-Network/JHMDB_dloader.py"
sample: 0 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/Documentario_Le_Parkour_Londrina_jump_f_nm_np1_ba_bad_1']
sample: 1 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/Documentario_Le_Parkour_Londrina_jump_f_nm_np1_le_bad_8']
sample: 2 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/Documentario_Le_Parkour_Londrina_jump_f_nm_np1_ri_bad_7']
Traceback (most recent call last):
  File "/home/mxz/pose_estimation/ECCV20 Key-Frame-Proposal-Network/JHMDB_dloader.py", line 411, in <module>
    for i, sample in enumerate(dloader):
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 218, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 218, in <listcomp>
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: double, float, float16, int64, int32, and uint8.`

situation 2: setting parameter, split as 'train'
`/ECCV20 Key-Frame-Proposal-Network/JHMDB_dloader.py"
sample: 0 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/35_pull_ups_pullup_f_nm_np1_fr_goo_0']
sample: 1 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/35_pull_ups_pullup_f_nm_np1_fr_goo_1']
sample: 2 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/35_pull_ups_pullup_f_nm_np1_fr_goo_2']
sample: 3 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/20_Marine_Corps_Pull_Ups_-_JimmyDShea_pullup_f_cm_np1_ba_bad_3']
sample: 4 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/20_Marine_Corps_Pull_Ups_-_JimmyDShea_pullup_f_cm_np1_ba_bad_4']
sample: 5 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/12_Pull-ups_by_female_athlete_pullup_f_cm_np1_ba_med_0']
sample: 6 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/12_Pull-ups_by_female_athlete_pullup_f_cm_np1_ba_med_1']
sample: 7 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/12_Pull-ups_by_female_athlete_pullup_f_cm_np1_ba_med_2']
sample: 8 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/10_Pull_Ups_pullup_f_nm_np1_fr_goo_0']
sample: 9 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/10_Pull_Ups_pullup_f_nm_np1_fr_goo_1']
sample: 10 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/10_Pull_Ups_pullup_f_nm_np1_fr_goo_2']
sample: 11 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/girl_pull_ups_fitness_exercise_pullups_pullup_f_cm_np1_fr_med_0']
sample: 12 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/girl_pull_ups_fitness_exercise_pullups_pullup_f_cm_np1_fr_med_1']
sample: 13 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/girl_pull_ups_fitness_exercise_pullups_pullup_f_cm_np1_fr_med_2']
sample: 14 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/22_Pull-ups_with_Speed_and_Perfect_Form_pullup_f_cm_np1_ba_med_0']
sample: 15 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/22_Pull-ups_with_Speed_and_Perfect_Form_pullup_f_cm_np1_ba_med_1']
sample: 16 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/pullup/22_Pull-ups_with_Speed_and_Perfect_Form_pullup_f_cm_np1_ba_med_2']
sample: 17 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/KUNG_FU_HUSTLE_jump_f_cm_np1_fr_bad_55']
sample: 18 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/St__Louis_Goalkeeping__Academy_elite_training_jump_f_nm_np1_le_bad_3']
sample: 19 imgSequence_to_use shape: torch.Size([1, 40, 3, 224, 224]) Bbox_to_use shape: torch.Size([1, 40, 4]) sequence_to_use shape: torch.Size([1, 40, 15, 2]) mask_idx: torch.Size([1, 40, 15, 2]) nframes shape: torch.Size([1]) imgPath shape: ['/home/mxz/pose_estimation/JHMDB/Rename_Images/jump/Arrasando_no_Le_Parkour_jump_f_cm_np1_le_bad_0']
Traceback (most recent call last):
  File "/home/mxz/pose_estimation/ECCV20 Key-Frame-Proposal-Network/JHMDB_dloader.py", line 411, in <module>
    for i, sample in enumerate(dloader):
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 218, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
  File "/home/mxz/anaconda3/envs/py36_torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 218, in <listcomp>
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: double, float, float16, int64, int32, and uint8.`

The error is the same.

Looking forward to your reply as soon as possible.

**Comment by Dream-s-Wang** [comment]
I change line 60 "bbox = scipy.io.loadmat(os.path.join(maskPath, 'Bbox.mat'))['Bbox']" to "bbox = scipy.io.loadmat(os.path.join(maskPath, 'Bbox.mat'))['Bbox'].astype('int64')".It worked.
